# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-16 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedRestaurants',
            fields=[
                ('id_vr', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant', models.ManyToManyField(to='forkilla.Restaurant')),
            ],
        ),
    ]
